# Generated by Django 4.1.4 on 2022-12-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='car_image',
            field=models.ImageField(blank=True, upload_to='none'),
        ),
    ]
