# Generated by Django 4.1.4 on 2022-12-27 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_alter_carinfo_car_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carinfo',
            old_name='cost_per_week',
            new_name='cost_per_day',
        ),
    ]
