# Generated by Django 4.1.4 on 2022-12-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_rename_cost_per_day_carinfo_price_carinfo_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
