# Generated by Django 4.1.4 on 2022-12-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0007_remove_customer_rental_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
