# Generated by Django 4.1.4 on 2023-02-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0008_alter_customer_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
    ]
