# Generated by Django 4.1.4 on 2022-12-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_rename_cost_per_week_carinfo_cost_per_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carinfo',
            old_name='cost_per_day',
            new_name='price',
        ),
        migrations.AddField(
            model_name='carinfo',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
